name: Deploy Lambda Function
on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    name: Deploy lambda function
    runs-on: [ ubuntu-latest]
    steps:
      - name: Configure AWS Credentials
        run:
          sleep 30
      - name: zip Lambda Function
        run: |
          sleep 30
      - name: AWS Deploy
        run: |
          sleep 180
